export enum UserRole {
  CREATE_CATEGORY = "CREATE_CATEGORY",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_CATEGORY = "DELETE_CATEGORY",
  DELETE_PRODUCT = "DELETE_PRODUCT",
}

export const ALL = "ALL"
